[package]
name = "diesel-aip-160-derive"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
description = "Derive macros for AIP-160 filtering with Diesel"
categories = ["database", "development-tools::procedural-macro-helpers"]
readme = "README.md"
documentation = "https://docs.rs/diesel-aip-160-derive"
publish = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "3", features = ["full"] }
